-- sieve
-- the sieve of Eratosthenes programmed with coroutines
-- typical usage : lua -e N=500 sieve.lua | column

-- generate all the numbers from 2 to n
function gen(n)
	return coroutine.wrap(function()
		for i=2, n do 
			coroutine.yield(i)
		end
	end)
end

-- filter the numbers generated by `g', removing multiples of `p'
function filter(p, g)
	return coroutine.wrap(function()
		for n in g do
			if n%p ~= 0 then
				coroutine.yield(n) 
			end
		end
	end)
end

N = N or 500			-- from command line
x = gen(N)				-- generate primes up to N
while 1 do
	local n = x()		-- pick a number until done
	if n == nil then 
		break
	end
	print(n)			-- must be a prime number 质数
	x = filter(n, x)	-- now remove its multiples
end

--[[
	关于语言的构成概念将用常见的扩展 BNF 表达式写出。
	也就是这个样子： {a} 意思是 0 或多个 a ， [a] 意思是一个可选的 a 。
	非最终的符号会保留原来的样子，关键字则看起来像这样 kword ，
	其它最终的符号则写成 `=´ 。 完整的 Lua 语法可以在本手册最后找到。
--]]